controller_list:
  - name: fake_LeftLeg_controller
    type: $(arg execution_type)
    joints:
      - L_leg_1
      - L_leg_2
      - L_leg_3
      - L_leg_4
      - L_leg_5
      - L_leg_6
  - name: fake_RightLeg_controller
    type: $(arg execution_type)
    joints:
      - R_leg_1
      - R_leg_2
      - R_leg_3
      - R_leg_4
      - R_leg_5
      - R_leg_6
  - name: fake_Legs_controller
    type: $(arg execution_type)
    joints:
      - L_leg_1
      - L_leg_2
      - L_leg_3
      - L_leg_4
      - L_leg_5
      - L_leg_6
      - R_leg_1
      - R_leg_2
      - R_leg_3
      - R_leg_4
      - R_leg_5
      - R_leg_6
  - name: fake_Head_controller
    type: $(arg execution_type)
    joints:
      - neck
      - head
  - name: fake_RightArm_controller
    type: $(arg execution_type)
    joints:
      - R_arm_1
      - R_arm_2
      - R_arm_3
  - name: fake_LeftArm_controller
    type: $(arg execution_type)
    joints:
      - L_arm_1
      - L_arm_2
      - L_arm_3
  - name: fake_Arms_controller
    type: $(arg execution_type)
    joints:
      - L_arm_1
      - L_arm_2
      - L_arm_3
      - R_arm_1
      - R_arm_2
      - R_arm_3
  - name: fake_All_controller
    type: $(arg execution_type)
    joints:
      - L_arm_1
      - L_arm_2
      - L_arm_3
      - L_leg_1
      - L_leg_2
      - L_leg_3
      - L_leg_4
      - L_leg_5
      - L_leg_6
      - R_arm_1
      - R_arm_2
      - R_arm_3
      - R_leg_1
      - R_leg_2
      - R_leg_3
      - R_leg_4
      - R_leg_5
      - R_leg_6
      - neck
      - head
initial:  # Define initial robot poses.
#  - group: LeftLeg
#    pose: home

  []