# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  L_arm_1:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  L_arm_2:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  L_arm_3:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  L_leg_1:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  L_leg_2:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  L_leg_3:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  L_leg_4:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  L_leg_5:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  L_leg_6:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  R_arm_1:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  R_arm_2:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  R_arm_3:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  R_leg_1:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  R_leg_2:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  R_leg_3:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  R_leg_4:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  R_leg_5:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  R_leg_6:
    has_velocity_limits: true
    max_velocity: 8
    has_acceleration_limits: false
    max_acceleration: 0
  head:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  neck:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0