# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - L_arm_1
    - L_arm_2
    - L_arm_3
    - L_leg_1
    - L_leg_2
    - L_leg_3
    - L_leg_4
    - L_leg_5
    - L_leg_6
    - R_arm_1
    - R_arm_2
    - R_arm_3
    - R_leg_1
    - R_leg_2
    - R_leg_3
    - R_leg_4
    - R_leg_5
    - R_leg_6
    - neck
    - head
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []