nuc:
  check_rate: 40  # Hz
  constraints:
    - source_topic: "camera/image_proc"
      warn_delay: 0.2
      error_delay: 1

jetson:
  check_rate: 40  # Hz
  constraints:
    - source_topic: "camera/image_proc"
      warn_delay: 0.2
      error_delay: 1
